(function () {
  'use strict';

  const DAY_MS = 86400000;
  let today = new Date('2026-09-20T09:00:00+05:30');
  let selectedPatientId = 'P-1002';
  let apiAvailable = false;
  let pendingAction = null;
  const API_BASE = window.DAI_API_BASE || `${location.protocol}//${location.hostname || 'localhost'}:3001/api`;
  const permissions = {
    admin: ['*'],
    doctor: ['brief_review', 'draft_edit', 'draft_review', 'priority', 'facility_review'],
    care_team: ['gap_contact', 'gap_reassign', 'gap_resolve', 'document_ingest', 'facility_review', 'sos_review'],
    front_desk: ['gap_contact', 'queue_manage', 'slot_reassign', 'sos_review']
  };
  let currentRole = localStorage.getItem('daiHospitalRole') || 'admin';

  let pathways = {
    maternal: { name: 'Maternal continuity', events: [
      { id:'anc-12', stage:'Trimester 1', type:'ANC visit', offset:84, requiredDocs:['visit_note'] },
      { id:'anomaly-scan', stage:'Trimester 2', type:'Anomaly scan', offset:140, requiredDocs:['scan_report'] },
      { id:'gtt', stage:'Trimester 2', type:'Glucose tolerance test', offset:168, requiredDocs:['lab_result'] },
      { id:'birth-plan', stage:'Trimester 3', type:'Birth plan readiness', offset:252, requiredDocs:['care_plan'] }
    ]},
    oncology: { name:'Oncology follow-up', events:[
      { id:'cycle-review', stage:'Cycle review', type:'Post-cycle review', offset:21, requiredDocs:['visit_note'] },
      { id:'cbc', stage:'Investigation', type:'CBC lab upload', offset:28, requiredDocs:['lab_result'] },
      { id:'scan-review', stage:'Follow-up imaging', type:'Follow-up scan filed', offset:90, requiredDocs:['imaging_report'] }
    ]},
    diabetes: { name:'Diabetes clinic', events:[
      { id:'hba1c', stage:'Quarterly labs', type:'HbA1c result upload', offset:90, requiredDocs:['lab_result'] },
      { id:'foot-check', stage:'Annual review', type:'Foot check recorded', offset:180, requiredDocs:['visit_note'] },
      { id:'eye-referral', stage:'Annual review', type:'Eye referral letter', offset:210, requiredDocs:['referral_letter'] }
    ]}
  };
  let patients = [
    { id:'P-1001', name:'Asha Nair', age:31, program:'maternal', provider:'Dr. S. Kumar', stage:'Trimester 2', pathwayStart:'2026-04-07', lastTouch:'2026-08-28', noShows:1, phone:'+91 90000 11111', consent:{documents:true,outreach:true} },
    { id:'P-1002', name:'Meera Joshi', age:28, program:'maternal', provider:'Dr. S. Kumar', stage:'Trimester 3', pathwayStart:'2025-12-10', lastTouch:'2026-08-02', noShows:3, phone:'+91 90000 22222', consent:{documents:true,outreach:true} },
    { id:'P-2030', name:'Farhan Ali', age:54, program:'diabetes', provider:'Dr. N. Rao', stage:'Quarterly labs', pathwayStart:'2026-02-08', lastTouch:'2026-08-14', noShows:2, phone:'+91 90000 33333', consent:{documents:true,outreach:true} },
    { id:'P-3091', name:'Leela Menon', age:47, program:'oncology', provider:'Dr. A. Shah', stage:'Follow-up imaging', pathwayStart:'2026-05-14', lastTouch:'2026-09-17', noShows:0, phone:'+91 90000 44444', consent:{documents:true,outreach:false} },
    { id:'P-3094', name:'Ritika Sen', age:39, program:'oncology', provider:'Dr. A. Shah', stage:'Investigation', pathwayStart:'2026-06-01', lastTouch:'2026-07-24', noShows:2, phone:'+91 90000 55555', consent:{documents:true,outreach:true} }
  ];
  let careEvents = [
    {patientId:'P-1001',type:'ANC visit',recordedAt:'2026-07-01',source:'EMR',documentRef:'visit-4401'},
    {patientId:'P-1001',type:'Anomaly scan',recordedAt:'2026-08-25',source:'Radiology',documentRef:'scan-8840'},
    {patientId:'P-1002',type:'ANC visit',recordedAt:'2026-03-10',source:'EMR',documentRef:'visit-4204'},
    {patientId:'P-1002',type:'Anomaly scan',recordedAt:'2026-05-01',source:'Radiology',documentRef:'scan-8322'},
    {patientId:'P-2030',type:'Foot check recorded',recordedAt:'2026-08-08',source:'EMR',documentRef:'visit-5180'},
    {patientId:'P-3091',type:'Post-cycle review',recordedAt:'2026-06-06',source:'EMR',documentRef:'visit-7731'},
    {patientId:'P-3091',type:'CBC lab upload',recordedAt:'2026-06-15',source:'Lab system',documentRef:'lab-9018'},
    {patientId:'P-3094',type:'Post-cycle review',recordedAt:'2026-06-25',source:'EMR',documentRef:'visit-7852'}
  ];
  let gapWork = {};
  let consultationBrief = {patientId:'P-1002',appointmentId:'A-902',status:'pending_review',facts:[
    {id:'F-1',label:'Last ANC visit',value:'2026-03-10',source:'EMR visit-4204',confidence:'typed/coded',status:'accepted'},
    {id:'F-2',label:'Anomaly scan document',value:'Uploaded 2026-05-01',source:'Radiology scan-8322',confidence:'typed/coded',status:'accepted'},
    {id:'F-3',label:'Referral letter',value:'Scan planned after 2026-08-15',source:'OCR doc-ref-192',confidence:'0.82',status:'pending_review'}
  ],flags:[{type:'missing_info',text:'No glucose tolerance test result found after expected date.',source:'Gap engine, pathway event gtt'}]};
  let queue = [
    {id:'A-902',slot:'09:30',patientId:'P-1002',status:'checked_in',waitMins:18,urgency:'Staff-set: high-priority follow-up',urgencySetBy:'Dr. S. Kumar'},
    {id:'A-903',slot:'09:45',patientId:'P-3091',status:'waiting',waitMins:11,urgency:'',urgencySetBy:''},
    {id:'A-904',slot:'10:00',patientId:'P-2030',status:'delayed_labs',waitMins:8,urgency:'',urgencySetBy:''},
    {id:'A-905',slot:'10:15',patientId:'P-1001',status:'cancelled',waitMins:0,urgency:'',urgencySetBy:''}
  ];
  let documents = [];
  let drafts = [{id:'D-501',type:'referral letter',language:'English',patientId:'P-1002',status:'pending_review',version:1,source:'Reviewed patient facts',body:'Draft referral letter assembled from reviewed demographics and listed document references.',reviewNotes:''}];
  let facilityCases = [{id:'FC-1',patientId:'P-1002',label:'Meera Joshi - expected delivery readiness',prioritySource:'Clinician-set',owner:'Labour ward coordinator',checklist:[{id:'staff',label:'Care team confirmed',ready:true,confirmedBy:'Dr. S. Kumar'},{id:'room',label:'Room availability confirmed',ready:false,confirmedBy:''},{id:'kit',label:'Delivery kit checked',ready:true,confirmedBy:'Nurse P. Roy'},{id:'transport',label:'Ambulance bay confirmed',ready:false,confirmedBy:''}]}];
  let sosRequests = [];
  let audit = [];

  const byId = (id) => document.getElementById(id);
  const esc = (value) => String(value == null ? '' : value).replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmtDate = (value) => new Date(value).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
  const addDays = (value,days) => new Date(new Date(value).getTime()+days*DAY_MS);
  const daysBetween = (a,b) => Math.floor((new Date(a).setHours(0,0,0,0)-new Date(b).setHours(0,0,0,0))/DAY_MS);
  const patient = (id) => patients.find((item)=>item.id===id);
  const can = (permission) => (permissions[currentRole]||[]).includes('*') || (permissions[currentRole]||[]).includes(permission);
  const actionButton = (permission, html) => can(permission) ? html : '';
  function localAudit(action,entityType,entityId,detail,before,after){audit.unshift({id:`AUD-${Date.now()}`,actor:'Dr. S. Kumar',role:currentRole,action,entityType,entityId,detail,before:before||null,after:after||null,timestamp:new Date().toISOString()});}
  function showToast(text){const el=byId('toast');el.textContent=text;el.classList.add('is-visible');clearTimeout(showToast.t);showToast.t=setTimeout(()=>el.classList.remove('is-visible'),2800);}
  async function api(path,options={}){const response=await fetch(API_BASE+'/hospital'+path,{...options,headers:{'Content-Type':'application/json','x-hospital-role':currentRole,'x-hospital-actor':'Dr. S. Kumar',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Hospital request failed.');return data;}
  function applyState(data){today=new Date(data.today||today);pathways=data.pathways||pathways;patients=data.patients||patients;careEvents=data.careEvents||careEvents;gapWork=data.gapWork||gapWork;consultationBrief=data.consultationBrief||consultationBrief;queue=data.queue||queue;documents=data.documents||documents;drafts=data.drafts||drafts;facilityCases=data.facilityCases||facilityCases;sosRequests=data.sosRequests||sosRequests;audit=data.audit||audit;if(!patient(selectedPatientId)&&patients.length)selectedPatientId=patients[0].id;}
  async function loadState(showStatus){try{applyState(await api('/state'));apiAvailable=true;if(showStatus)showToast('Hospital backend connected.');}catch(_){apiAvailable=false;if(showStatus)showToast('Using local demo data. Start the backend to save changes.');}}
  async function post(path,payload){if(!apiAvailable)return null;try{const result=await api(path,{method:'POST',body:JSON.stringify({...payload,role:currentRole,actor:'Dr. S. Kumar'})});if(result.state)applyState(result.state);return result;}catch(error){showToast(error.message);return false;}}

  function computeGaps(){const rows=[];patients.forEach((p)=>{(pathways[p.program]?.events||[]).forEach((expected)=>{const due=addDays(p.pathwayStart,expected.offset);const actual=careEvents.find((event)=>event.patientId===p.id&&event.type===expected.type&&new Date(event.recordedAt)<=today);const id=`${p.id}:${expected.id}`;const work=gapWork[id]||{};const overdue=daysBetween(today,due);if(!actual&&overdue>0&&!work.resolvedAt)rows.push({id,patientId:p.id,patientName:p.name,program:p.program,provider:p.provider,stage:expected.stage,expectedType:expected.type,dueDate:due.toISOString().slice(0,10),daysOverdue:overdue,assignedTo:work.assignedTo||p.provider,contacts:work.contacts||[],operationalPriority:overdue+p.noShows*7,provenance:`Expected ${expected.id} in ${pathways[p.program].name}; no matching recorded event found.`});});});return rows.sort((a,b)=>b.operationalPriority-a.operationalPriority);}
  function timelineFor(id){const p=patient(id);if(!p)return[];return pathways[p.program].events.map((expected)=>{const due=addDays(p.pathwayStart,expected.offset);const event=careEvents.find((item)=>item.patientId===id&&item.type===expected.type);const work=gapWork[`${id}:${expected.id}`]||{};return{...expected,dueDate:due.toISOString().slice(0,10),status:event?'completed':work.resolvedAt?'resolved':due<today?'overdue':'upcoming',event};});}

  function populateControls(){const programs=Object.keys(pathways);const providers=[...new Set(patients.map((p)=>p.provider))];const assignees=[...new Set([...providers,'Care coordinator','Front desk team'])];byId('programFilter').innerHTML='<option value="">All programs</option>'+programs.map((key)=>`<option value="${key}">${esc(pathways[key].name)}</option>`).join('');byId('providerFilter').innerHTML='<option value="">All providers</option>'+providers.map((name)=>`<option>${esc(name)}</option>`).join('');byId('assignedFilter').innerHTML='<option value="">All assignees</option>'+assignees.map((name)=>`<option>${esc(name)}</option>`).join('');byId('documentPatient').innerHTML=patients.map((p)=>`<option value="${p.id}">${esc(p.name)} - ${p.id}</option>`).join('');byId('sosPatient').innerHTML=byId('documentPatient').innerHTML;byId('pathwayProgram').innerHTML=programs.map((key)=>`<option value="${key}">${esc(pathways[key].name)}</option>`).join('');byId('currentRole').value=currentRole;}
  function filteredPatients(){const program=byId('programFilter').value,provider=byId('providerFilter').value,assigned=byId('assignedFilter').value,overdue=Number(byId('overdueFilter').value),search=byId('searchInput').value.trim().toLowerCase();return patients.filter((p)=>{const gaps=computeGaps().filter((g)=>g.patientId===p.id&&g.daysOverdue>overdue&&(!assigned||g.assignedTo===assigned));return(!program||p.program===program)&&(!provider||p.provider===provider)&&(!overdue&&!assigned||gaps.length)&&(!search||(p.name+' '+p.id).toLowerCase().includes(search));});}
  function renderMetrics(){const gaps=computeGaps();const pending=drafts.filter((d)=>!['approved','published'].includes(d.status)).length+(consultationBrief.status==='reviewed'?0:1);const metrics=[['Open care gaps',gaps.length,'Assignable follow-up work'],['Patients in panel',patients.length,`${Object.keys(pathways).length} active programs`],['Pending reviews',pending,'Briefs and drafts'],['Active SOS',sosRequests.filter((s)=>!['accepted','declined'].includes(s.status)).length,'Verified response workflow']];byId('metrics').innerHTML=metrics.map((m)=>`<div class="panel metric"><span>${m[0]}</span><b>${m[1]}</b><em>${m[2]}</em></div>`).join('');}
  function renderRegistry(){const rows=filteredPatients();byId('registryRows').innerHTML=rows.map((p)=>{const gaps=computeGaps().filter((g)=>g.patientId===p.id);const score=gaps.reduce((sum,g)=>sum+g.operationalPriority,0);return`<tr class="${p.id===selectedPatientId?'is-selected':''}" data-patient="${p.id}"><td><div class="patient-name">${esc(p.name)}</div><div class="subtle">${p.id} · Age ${p.age}</div></td><td>${esc(pathways[p.program].name)}</td><td>${esc(p.stage)}</td><td>${gaps.length?`<span class="tag tag-red">${gaps.length} open</span>`:'<span class="tag tag-green">none</span>'}</td><td>${fmtDate(p.lastTouch)}</td><td><span class="tag tag-amber">${score}</span><div class="subtle">operational only</div></td></tr>`;}).join('')||'<tr><td colspan="6"><div class="empty">No matching patients.</div></td></tr>';renderPatientDetail();}
  function renderPatientDetail(){const p=patient(selectedPatientId)||patients[0];const gaps=computeGaps().filter((g)=>g.patientId===p.id);const timeline=timelineFor(p.id);byId('patientDetail').innerHTML=`<div><h3>${esc(p.name)}</h3><div class="subtle">${p.id} · ${esc(pathways[p.program].name)} · ${esc(p.provider)}</div></div><div class="status-line"><span class="tag tag-blue">${esc(p.stage)}</span><span class="tag tag-gray">Last touch ${fmtDate(p.lastTouch)}</span></div><div class="detail-block"><h4>Open care gaps</h4><div class="detail-list">${gaps.length?gaps.map((g)=>`<div class="gap-card"><strong>${esc(g.expectedType)}</strong><p>Due ${fmtDate(g.dueDate)} · ${g.daysOverdue} days overdue · assigned to ${esc(g.assignedTo)}</p><p>Provenance: ${esc(g.provenance)}</p>${g.contacts.length?`<p>Latest contact: ${esc(g.contacts[g.contacts.length-1].outcome)}</p>`:''}<div class="btn-row compact-actions">${actionButton('gap_contact',`<button class="btn btn-primary" data-action="contact" data-gap="${g.id}">Record contact</button>`)}${actionButton('gap_reassign',`<button class="btn" data-action="reassign" data-gap="${g.id}">Reassign</button>`)}${actionButton('gap_resolve',`<button class="btn btn-ok" data-action="resolve" data-gap="${g.id}">Resolve</button>`)}</div></div>`).join(''):'<div class="empty">No open gaps.</div>'}</div></div><div class="detail-block"><h4>Care timeline</h4><div class="timeline-list">${timeline.map((item)=>`<div class="timeline-item"><span class="timeline-dot ${item.status}"></span><div><strong>${esc(item.title)}</strong><p>${esc(item.stage)} · due ${fmtDate(item.dueDate)}${item.event?` · recorded ${fmtDate(item.event.recordedAt)} from ${esc(item.event.source)}`:''}</p></div><span class="tag ${item.status==='completed'||item.status==='resolved'?'tag-green':item.status==='overdue'?'tag-red':'tag-gray'}">${item.status}</span></div>`).join('')}</div></div>`;}
  function renderBrief(){byId('briefStatus').textContent=consultationBrief.status.replaceAll('_',' ');byId('briefStatus').className='tag '+(consultationBrief.status==='reviewed'?'tag-green':consultationBrief.status==='needs_correction'?'tag-red':'tag-violet');byId('briefFacts').innerHTML=consultationBrief.facts.map((f)=>`<div class="fact ${f.status==='rejected'?'is-rejected':''}"><strong>${esc(f.label)}: ${esc(f.value)}</strong><p>Source: ${esc(f.source)} · Confidence: ${esc(f.confidence)}</p><div class="status-line"><span class="tag ${f.status==='rejected'?'tag-red':'tag-gray'}">${esc(f.status)}</span>${actionButton('brief_review',`<button class="btn btn-danger btn-small" data-action="reject-fact" data-fact="${f.id}">Reject fact</button>`)}</div></div>`).join('');byId('briefFlags').innerHTML=consultationBrief.flags.map((f)=>`<div class="fact"><strong>${esc(f.type.replaceAll('_',' '))}</strong><p>${esc(f.text)}</p><p>Source: ${esc(f.source)}</p></div>`).join('')||'<div class="empty">No missing or inconsistent information.</div>';}
  function renderClinic(){byId('queueList').innerHTML=queue.map((q)=>{const p=patient(q.patientId);return`<div class="queue-card"><strong>${q.slot} · ${esc(p?.name||'Open slot')}</strong><p>Status: ${esc(q.status.replaceAll('_',' '))} · waiting ${q.waitMins} min</p>${q.urgency?`<p><span class="tag tag-red">${esc(q.urgency)}</span></p>`:'<p><span class="tag tag-gray">No manual urgency</span></p>'}${actionButton('queue_manage',`<div class="inline-controls"><select data-queue-status="${q.id}">${['scheduled','checked_in','waiting','in_consultation','completed','cancelled','delayed_labs'].map((s)=>`<option value="${s}" ${s===q.status?'selected':''}>${s.replaceAll('_',' ')}</option>`).join('')}</select><button class="btn" data-action="save-queue" data-queue="${q.id}">Update</button><button class="btn" data-action="toggle-urgency" data-queue="${q.id}">${q.urgency?'Clear urgency':'Set urgency'}</button></div>`)}</div>`;}).join('');const cancelled=queue.find((q)=>q.status==='cancelled');byId('slotSuggestions').innerHTML=computeGaps().slice(0,3).map((g)=>`<div class="queue-card"><strong>${cancelled?cancelled.slot:'Next opening'} suggestion: ${esc(g.patientName)}</strong><p>${g.daysOverdue} days overdue. Staff must approve; this is not an automatic booking.</p>${actionButton('slot_reassign',`<button class="btn btn-primary" data-action="approve-slot" data-gap="${g.id}">Approve slot</button>`)}</div>`).join('')||'<div class="empty">No outreach suggestions.</div>';}
  function statusClass(status){return ['approved','published'].includes(status)?'tag-green':status==='rejected'?'tag-red':status==='pending_review'?'tag-violet':'tag-gray';}
  function renderDrafts(){byId('draftCards').innerHTML=drafts.map((d)=>`<article class="panel draft-card"><div class="status-line"><span class="tag tag-blue">${esc(d.type)}</span><span class="tag ${statusClass(d.status)}">${esc(d.status.replaceAll('_',' '))}</span></div><label class="mini-label">Editable content · version ${d.version||1} · ${esc(d.language||'English')}</label><textarea class="draft-editor" data-draft-body="${d.id}" ${d.status==='published'?'disabled':''}>${esc(d.body)}</textarea><p>Source: ${esc(d.source||'Approved source')}</p><div class="btn-row">${actionButton('draft_edit',d.status!=='published'?`<button class="btn" data-action="save-draft" data-draft="${d.id}">Save edit</button>`:'')}${actionButton('draft_review',['draft','pending_review'].includes(d.status)?`<button class="btn btn-ok" data-action="approve-draft" data-draft="${d.id}">Approve</button>`:'')}${actionButton('draft_review',d.status==='approved'?`<button class="btn btn-primary" data-action="publish-draft" data-draft="${d.id}">Publish/file</button>`:'')}${actionButton('draft_review',d.status!=='published'?`<button class="btn btn-danger" data-action="reject-draft" data-draft="${d.id}">Reject</button>`:'')}</div></article>`).join('');}
  function renderFacility(){byId('facilityCases').innerHTML=facilityCases.map((c)=>`<div class="queue-card"><strong>${esc(c.label)}</strong><p>${esc(c.prioritySource)} · owner: ${esc(c.owner)}</p>${c.checklist.map((item)=>`<div class="check-row"><span>${esc(item.label)}${item.confirmedBy?` · ${esc(item.confirmedBy)}`:''}</span>${actionButton('facility_review',`<button class="btn ${item.ready?'btn-ok':''}" data-action="toggle-readiness" data-case="${c.id}" data-item="${item.id}" data-ready="${item.ready}">${item.ready?'Ready':'Confirm'}</button>`)}</div>`).join('')}</div>`).join('');byId('sosRows').innerHTML=sosRequests.map((s)=>{const p=patient(s.patientId);return`<div class="queue-card"><strong>${esc(p?.name||s.patientId)} · ${esc(s.status.replaceAll('_',' '))}</strong><p>${esc(s.location)} · ${new Date(s.createdAt).toLocaleString('en-IN')}</p><div class="btn-row">${s.status==='awaiting_verification'?actionButton('sos_review',`<button class="btn btn-ok" data-action="verify-sos" data-sos="${s.id}">Verify request</button>`):''}${s.status==='verified'?actionButton('sos_review',`<button class="btn btn-primary" data-action="respond-sos" data-sos="${s.id}">Accept</button><button class="btn btn-danger" data-action="decline-sos" data-sos="${s.id}">Decline</button>`):''}</div></div>`;}).join('')||'<div class="empty">No active emergency requests.</div>';}
  function renderPathways(){byId('pathwayCards').innerHTML=Object.keys(pathways).map((key)=>`<article class="panel detail-block"><h4>${esc(pathways[key].name)}</h4>${pathways[key].events.map((e)=>`<div class="fact"><strong>${esc(e.type)}</strong><p>${esc(e.stage)} · day ${e.offset} · documents: ${esc(e.requiredDocs.join(', ')||'none')}</p></div>`).join('')}</article>`).join('');}
  function renderAudit(){const actorFilter=byId('auditActor').value.trim().toLowerCase(),actionFilter=byId('auditAction').value.trim().toLowerCase(),entityFilter=byId('auditEntity').value.trim().toLowerCase(),dateFilter=byId('auditDate').value;const rows=audit.filter((a)=>(!actorFilter||a.actor.toLowerCase().includes(actorFilter))&&(!actionFilter||a.action.toLowerCase().includes(actionFilter))&&(!entityFilter||(a.entityId+' '+a.entityType).toLowerCase().includes(entityFilter))&&(!dateFilter||a.timestamp.slice(0,10)===dateFilter));byId('auditRows').innerHTML=rows.slice(0,50).map((a)=>`<div class="audit-row"><strong>${esc(a.actor)} · ${esc(a.action)}</strong><p>${esc(a.role||'user')} · ${esc(a.entityType)} ${esc(a.entityId)} · ${new Date(a.timestamp).toLocaleString('en-IN')}</p><p>${esc(a.detail)}</p></div>`).join('')||'<div class="empty">No matching audit events.</div>';}
  function rerender(){renderMetrics();renderRegistry();renderBrief();renderClinic();renderDrafts();renderFacility();renderPathways();renderAudit();document.querySelectorAll('[data-permission]').forEach((el)=>el.hidden=!can(el.dataset.permission));}

  function openModal(title,copy,fields,confirm){pendingAction=confirm;byId('modalTitle').textContent=title;byId('modalCopy').textContent=copy;byId('modalFields').innerHTML=fields.map((f)=>`<div class="control"><label for="modal-${f.name}">${esc(f.label)}</label>${f.type==='select'?`<select id="modal-${f.name}" data-modal-field="${f.name}">${f.options.map((o)=>`<option value="${esc(o.value||o)}">${esc(o.label||o)}</option>`).join('')}</select>`:f.type==='textarea'?`<textarea id="modal-${f.name}" data-modal-field="${f.name}" placeholder="${esc(f.placeholder||'')}"></textarea>`:`<input id="modal-${f.name}" data-modal-field="${f.name}" type="${f.type||'text'}" placeholder="${esc(f.placeholder||'')}">`}</div>`).join('');byId('actionModal').classList.add('is-open');}
  function closeModal(){byId('actionModal').classList.remove('is-open');pendingAction=null;}
  function modalValues(){const values={};document.querySelectorAll('[data-modal-field]').forEach((field)=>values[field.dataset.modalField]=field.value.trim());return values;}
  async function runGapAction(action,id){const gap=computeGaps().find((g)=>g.id===id);if(!gap)return;if(action==='contact')openModal('Record contact',`${gap.patientName} · ${gap.expectedType}`,[{name:'method',label:'Contact method',type:'select',options:['phone','SMS','WhatsApp','email']},{name:'outcome',label:'Outcome',type:'select',options:['reached','left message','no answer','wrong number']},{name:'notes',label:'Notes',type:'textarea'}],async(v)=>{const result=await post(`/gaps/${encodeURIComponent(id)}/contact`,v);if(result===null){gapWork[id]=gapWork[id]||{assignedTo:gap.assignedTo,contacts:[]};gapWork[id].contacts.push({...v,at:new Date().toISOString()});localAudit('gap_contacted','CareGap',id,`${v.method}: ${v.outcome}`);}if(result!==false){showToast('Contact outcome saved.');rerender();}});if(action==='reassign')openModal('Reassign follow-up',`${gap.patientName} · currently ${gap.assignedTo}`,[{name:'assignedTo',label:'New assignee',type:'select',options:['Dr. S. Kumar','Dr. N. Rao','Dr. A. Shah','Care coordinator','Front desk team']},{name:'notes',label:'Reason',type:'textarea'}],async(v)=>{const result=await post(`/gaps/${encodeURIComponent(id)}/reassign`,v);if(result===null){gapWork[id]=gapWork[id]||{contacts:[]};gapWork[id].assignedTo=v.assignedTo;localAudit('gap_reassigned','CareGap',id,v.notes||`Assigned to ${v.assignedTo}`);}if(result!==false){showToast('Follow-up reassigned.');rerender();}});if(action==='resolve')openModal('Resolve care gap',`${gap.patientName} · ${gap.expectedType}`,[{name:'notes',label:'Resolution notes',type:'textarea',placeholder:'What was completed?'},{name:'evidence',label:'Evidence or document reference',placeholder:'Report, visit or document ID'}],async(v)=>{if(!v.notes||!v.evidence)return showToast('Resolution notes and evidence are required.');const result=await post(`/gaps/${encodeURIComponent(id)}/resolve`,v);if(result===null){gapWork[id]={...(gapWork[id]||{}),resolvedAt:new Date().toISOString(),resolutionNotes:v.notes,evidence:v.evidence};localAudit('gap_resolved','CareGap',id,v.notes);}if(result!==false){showToast('Gap resolved; next milestone is visible.');rerender();}});}

  document.addEventListener('click',async(e)=>{
    const row=e.target.closest('tr[data-patient]');if(row){selectedPatientId=row.dataset.patient;localAudit('record_accessed','Patient',selectedPatientId,'Opened patient details.');renderRegistry();renderAudit();return;}
    const button=e.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;
    if(action==='close-modal')return closeModal();
    if(action==='confirm-modal'&&pendingAction){const values=modalValues(),run=pendingAction;closeModal();await run(values);return;}
    if(button.dataset.gap&&['contact','reassign','resolve'].includes(action))return runGapAction(action,button.dataset.gap);
    if(action==='approve-slot'){const result=await post(`/clinic/slots/${encodeURIComponent(button.dataset.gap)}/reassign`,{});if(result===null){const gap=computeGaps().find((g)=>g.id===button.dataset.gap),slot=queue.find((q)=>q.status==='cancelled');if(slot&&gap){slot.patientId=gap.patientId;slot.status='scheduled';localAudit('slot_reassigned','Appointment',slot.id,`${slot.slot} assigned to ${gap.patientName}.`);}}if(result!==false){showToast('Slot reassigned and notification queued.');rerender();}}
    if(action==='save-queue'){const id=button.dataset.queue,status=document.querySelector(`[data-queue-status="${id}"]`).value;const result=await post(`/clinic/queue/${id}/status`,{status});if(result===null){const item=queue.find((q)=>q.id===id);item.status=status;localAudit('queue_status_updated','Appointment',id,`Status changed to ${status}.`);}if(result!==false){showToast('Queue updated.');rerender();}}
    if(action==='toggle-urgency'){const item=queue.find((q)=>q.id===button.dataset.queue);const urgency=item.urgency?'':'Staff-set urgent follow-up';const result=await post(`/clinic/queue/${item.id}/urgency`,{urgency});if(result===null){item.urgency=urgency;localAudit('manual_urgency_updated','Appointment',item.id,urgency||'Urgency cleared.');}if(result!==false){showToast('Manual urgency updated.');rerender();}}
    if(action==='review-brief'){const result=await post(`/consultations/${consultationBrief.appointmentId}/brief/review`,{});if(result===null){consultationBrief.status='reviewed';localAudit('brief_reviewed','ConsultationBrief',consultationBrief.appointmentId,'Brief reviewed.');}if(result!==false){showToast('Brief reviewed.');rerender();}}
    if(action==='reject-fact')openModal('Reject extracted fact','The fact will be returned for correction.',[{name:'notes',label:'Correction reason',type:'textarea'}],async(v)=>{const result=await post(`/consultations/${consultationBrief.appointmentId}/facts/${button.dataset.fact}/reject`,v);if(result===null){const fact=consultationBrief.facts.find((f)=>f.id===button.dataset.fact);fact.status='rejected';fact.reviewNotes=v.notes;consultationBrief.status='needs_correction';localAudit('brief_fact_rejected','BriefFact',fact.id,v.notes);}if(result!==false){showToast('Fact rejected for correction.');rerender();}});
    if(action==='new-draft')openModal('Generate draft','Every generated item remains a draft until a clinician approves it.',[{name:'type',label:'Draft type',type:'select',options:['referral letter','patient handout','department report']},{name:'language',label:'Language',type:'select',options:['English','Hindi','Malayalam']},{name:'source',label:'Approved source',placeholder:'Knowledge base or reviewed patient facts'}],async(v)=>{const payload={...v,body:'New draft created from approved hospital source material. Review and edit before publication.'};const result=await post('/content/draft',payload);if(result===null){drafts.unshift({id:`D-${Date.now()}`,patientId:null,status:'draft',version:1,reviewNotes:'',...payload});localAudit('draft_generated','ContentDraft',drafts[0].id,'Draft generated.');}if(result!==false){showToast('Draft generated for review.');rerender();}});
    if(action==='save-draft'){const draft=drafts.find((d)=>d.id===button.dataset.draft),body=document.querySelector(`[data-draft-body="${draft.id}"]`).value;const result=await post(`/content/${draft.id}/edit`,{body,language:draft.language});if(result===null){draft.body=body;draft.version=(draft.version||1)+1;draft.status='pending_review';localAudit('draft_edited','ContentDraft',draft.id,'Draft edited.');}if(result!==false){showToast('Draft saved and returned to review.');rerender();}}
    if(['approve-draft','reject-draft','publish-draft'].includes(action)){const draft=drafts.find((d)=>d.id===button.dataset.draft),verb=action.split('-')[0];openModal(`${verb[0].toUpperCase()+verb.slice(1)} draft`,`${draft.id} · version ${draft.version}`,[{name:'notes',label:'Review notes',type:'textarea'}],async(v)=>{const result=await post(`/content/${draft.id}/${verb}`,v);if(result===null){if(verb==='publish'&&draft.status!=='approved')return showToast('Approve the draft before publishing.');draft.status=verb==='approve'?'approved':verb==='reject'?'rejected':'published';draft.reviewNotes=v.notes;localAudit(`draft_${verb}d`,'ContentDraft',draft.id,v.notes||`Draft ${draft.status}.`);}if(result!==false){showToast('Draft status updated.');rerender();}});}
    if(action==='toggle-readiness'){const ready=button.dataset.ready!=='true';const result=await post(`/facility/${button.dataset.case}/items/${button.dataset.item}/toggle`,{ready});if(result===null){const item=facilityCases.find((c)=>c.id===button.dataset.case).checklist.find((i)=>i.id===button.dataset.item);item.ready=ready;item.confirmedBy=ready?'Dr. S. Kumar':'';localAudit('facility_readiness_updated','FacilityCase',button.dataset.case,`${item.label}: ${ready?'ready':'not ready'}.`);}if(result!==false){showToast('Readiness updated.');rerender();}}
    if(action==='verify-sos'||action==='respond-sos'||action==='decline-sos'){const path=action==='verify-sos'?'authenticate':'respond',payload=action==='decline-sos'?{response:'decline'}:{response:'accept'};const result=await post(`/sos/${button.dataset.sos}/${path}`,payload);if(result===null){const sos=sosRequests.find((s)=>s.id===button.dataset.sos);sos.status=action==='verify-sos'?'verified':action==='decline-sos'?'declined':'accepted';localAudit(`sos_${path}`,'SOSRequest',sos.id,`SOS ${sos.status}.`);}if(result!==false){showToast('SOS workflow updated.');rerender();}}
  });

  byId('documentForm').addEventListener('submit',async(e)=>{e.preventDefault();const file=byId('documentInput').files[0];if(!file)return showToast('Choose a document first.');const payload={patientId:byId('documentPatient').value,name:file.name,type:byId('documentType').value,factLabel:'Uploaded '+byId('documentType').selectedOptions[0].text,factValue:file.name};const result=await post('/documents/ingest',payload);if(result===null){const doc={id:`DOC-${Date.now()}`,...payload,uploadedAt:new Date().toISOString(),status:'pending_review',source:'Hospital upload'};documents.unshift(doc);if(consultationBrief.patientId===payload.patientId)consultationBrief.facts.push({id:`F-${Date.now()}`,label:payload.factLabel,value:payload.factValue,source:`Hospital upload ${doc.id}`,confidence:'demo extraction - review required',status:'pending_review'});localAudit('document_ingested','Document',doc.id,'Document uploaded and fact extracted.');}if(result!==false){e.target.reset();showToast('Document added; extracted fact needs review.');rerender();}});
  byId('sosForm').addEventListener('submit',async(e)=>{e.preventDefault();if(!byId('sosConsent').checked)return showToast('Confirm consent before creating an SOS request.');const payload={patientId:byId('sosPatient').value,location:byId('sosLocation').value||'Location shared with consent',consentConfirmed:true};const result=await post('/sos/trigger',payload);if(result===null){const sos={id:`SOS-${Date.now()}`,...payload,status:'awaiting_verification',createdAt:new Date().toISOString()};sosRequests.unshift(sos);localAudit('sos_received','SOSRequest',sos.id,'SOS received; verification required.');}if(result!==false){showToast('SOS received and awaiting verification.');rerender();}});
  byId('pathwayForm').addEventListener('submit',async(e)=>{e.preventDefault();const program=byId('pathwayProgram').value,payload={type:byId('pathwayEvent').value,stage:byId('pathwayStage').value,offset:Number(byId('pathwayOffset').value),requiredDocs:byId('pathwayDocs').value.split(',').map((x)=>x.trim()).filter(Boolean)};if(!payload.type||!payload.offset)return showToast('Add an event name and day offset.');const result=await post(`/pathways/${program}/events`,payload);if(result===null){pathways[program].events.push({id:`custom-${Date.now()}`,...payload});localAudit('pathway_event_added','CarePathway',program,`Added ${payload.type}.`);}if(result!==false){e.target.reset();showToast('Pathway event added.');populateControls();rerender();}});
  ['programFilter','providerFilter','assignedFilter','overdueFilter','searchInput'].forEach((id)=>{byId(id).addEventListener('input',renderRegistry);byId(id).addEventListener('change',renderRegistry);});
  ['auditActor','auditAction','auditEntity','auditDate'].forEach((id)=>{byId(id).addEventListener('input',renderAudit);byId(id).addEventListener('change',renderAudit);});
  byId('currentRole').addEventListener('change',(e)=>{currentRole=e.target.value;localStorage.setItem('daiHospitalRole',currentRole);showToast(`Viewing as ${currentRole.replaceAll('_',' ')}.`);rerender();});
  document.querySelectorAll('.nav a').forEach((link)=>link.addEventListener('click',()=>{document.querySelectorAll('.nav a').forEach((a)=>a.classList.remove('is-active'));link.classList.add('is-active');}));

  loadState(true).then(()=>{populateControls();rerender();});
})();
